# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e4ff188d7b5ec9e2d0cdae9de0cc8ee5"
application_url = "https://alfred-appreciate-possess-profession.trycloudflare.com"
embedded = true
name = "InfiConnect"
handle = "inficonnect"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_orders,read_customers,write_customers,read_products"

[auth]
redirect_urls = [
  "https://alfred-appreciate-possess-profession.trycloudflare.com/auth/callback",
  "https://alfred-appreciate-possess-profession.trycloudflare.com/auth/shopify/callback",
  "https://alfred-appreciate-possess-profession.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
